# Generated by Django 6.0.8 on 2026-08-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграмм chat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграмм chat-id",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                blank=True, help_text="Укажите телеграм ник", max_length=50, null=True, verbose_name="TG name"
            ),
        ),
    ]
