# Generated by Django 6.1 on 2026-08-28 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(help_text="Укажите место", max_length=100, verbose_name="Место")),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите когда будет выполняться привычка", verbose_name="Время начала"
                    ),
                ),
                (
                    "action",
                    models.TextField(help_text="Укажите что представляет собой привычка", verbose_name="Действие"),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1, help_text="Укажите периодичность привычки", verbose_name="Периодичность"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=100,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "action_time",
                    models.PositiveIntegerField(
                        help_text="Укажите время на выполнение привычки", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Укажите публичная ли привычка", verbose_name="Публичность"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, help_text="Укажите приятная ли привычка", verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя привычки",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
